[package]
name = "gtf_splice_index"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.9"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
bincode = "1"
zstd = "0.13"